api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations

    formats:
        json:     ['application/json']
        html:     ['text/html']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']

    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header